name: linux build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

jobs:
  linux:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/julianharbarth/docker-cpp-build:master
      volumes:
        - ${{ matrix.config.preset }}-deps:/deps
        - ${{ matrix.config.preset }}-buildcache:/buildcache
    strategy:
      fail-fast: false
      matrix:
        config:
          - preset: clang-debug
          - preset: clang-release
            artifact: linux-amd64
          - preset: gcc-debug
          - preset: gcc-release
          - preset: gcc-cista-debug
          - preset: gcc-cista-release
          - preset: clang-cista-debug
          - preset: clang-cista-release
          - preset: clang-sanitizer
          - preset: clang-cista-sanitizer
    env:
      BUILDCACHE_DIR: /buildcache
      BUILDCACHE_DIRECT_MODE: true
      BUILDCACHE_MAX_CACHE_SIZE: 26843545600
      BUILDCACHE_LUA_PATH: ${{ github.workspace }}/tools

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: build soro-s
        uses: ./.github/actions/build-soro-s
        with:
          preset: ${{ matrix.config.preset }}

      - name: test soro-s
        uses: ./.github/actions/test-soro-s

      - name: create and upload artifact
        if: matrix.config.artifact
        uses: ./.github/actions/create-artifact
        with:
          preset: ${{ matrix.config.preset }}
          artifact: ${{ matrix.config.artifact }}

  ui-tests:
    ui-tests:
      needs: linux
      runs-on: ubuntu-latest
    services:
      selenium-hub:
        image: selenium/hub:4.7.2-20221219
        ports:
          - 4442:4442
          - 4443:4443
          - 4444:4444
      chrome:
        image: selenium/node-chrome:4.7.2-20221219
        options: --shm-size="2g" --add-host host.docker.internal:host-gateway
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      firefox:
        image: selenium/node-firefox:4.7.2-20221219
        options: --shm-size="2g" --add-host host.docker.internal:host-gateway
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    steps:
      - name: checkout repository
      - uses: actions/checkout@v3

      - name: cache python dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: install python dependencies
        run: pip install -r ui-test/requirements.txt

      - name: download soro-s artifact
        uses: actions/download-artifact@v3
        with:
          name: soro-server

      - name: prepare soro-server
        run: chmod +x soro-server

        # TODO(julian) remove?
      - name: check hostname
        run: hostname

      - name: run ui tests
        run: |
          find web/client/ui-test -type f -executable -name '*.py' -print0 | xargs -0 -n1 python3

  docker:
    if: github.event.action == 'published'
    runs-on: ubuntu-22.04
    needs: [ ui-tests, linux ]

    steps:
      - name: create and upload docker image
        uses: ./.github/actions/soro-s-docker